services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4Emperador
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: